In [ ]:
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd

In [ ]:
#import os
#os.getcwd() : change working directory

In [ ]:
#importing the dataset
dataset = pd.read_csv("/content/demo1.csv")

In [ ]:
x = dataset.iloc[:, [1, 2]].values
x

array([[1011,  953],
       [1012,  983],
       [1012,  980],
       [1013,  975],
       [1013,  970],
       [1013,  971],
       [1015,  969],
       [1017,  967],
       [1017,  968],
       [1016,  966],
       [1012,  933],
       [1010,  937],
       [1012,  940],
       [1013,  945],
       [1008,  924],
       [1007,  595],
       [ 771,  767],
       [ 741,  748],
       [ 752,  722],
       [ 733,  813],
       [ 731,  767],
       [ 249,  261],
       [ 325,  344],
       [1011,  991],
       [1010,  487],
       [1012,  572],
       [1018, 1016],
       [1016, 1023],
       [ 511, 1018],
       [1014, 1020],
       [1011, 1016],
       [1010, 1013],
       [1011, 1014],
       [1012, 1016],
       [ 897,  508],
       [ 781,  534],
       [ 746,  512],
       [ 306,  255],
       [ 198,  175],
       [ 490,  457],
       [ 788,  514],
       [ 959, 1016],
       [ 976, 1016],
       [ 983, 1015],
       [ 976, 1016],
       [ 971, 1015],
       [ 973, 1015],
       [ 976,

In [ ]:
y = dataset.iloc[:, 3].values
y

array(['d', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'm', 'm', 'm', 'm', 'm', 'w', 'w', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'm', 'm', 'm', 'w', 'w',
       'w', 'm', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'd', 'd', 'd', 'd', 'd'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)
print(x_test)

[[ 0.28660539  0.42614851]
 [ 0.33277308  0.44227276]
 [ 0.24043769  0.37240101]
 [ 0.29320077  0.40464951]
 [ 0.3261777   0.43689801]
 [ 0.45808539  0.049916  ]
 [ 0.21405615  0.43152326]
 [ 0.3261777   0.44764751]
 [ 0.28001     0.39390001]
 [ 0.33277308  0.45839702]
 [ 0.41851308 -1.83124659]
 [ 0.30639154  0.41539901]
 [-1.0258762  -2.26660135]
 [ 0.28001     0.39390001]
 [ 0.29979616  0.41002426]
 [ 0.45808539  0.2111585 ]
 [ 0.28660539  0.39927476]
 [ 0.33277308  0.44764751]
 [ 0.47127616  0.17891   ]
 [ 0.33277308  0.46914652]
 [ 0.28001     0.39390001]
 [ 0.30639154  0.43152326]
 [ 0.26022385  0.38852526]
 [ 0.29979616  0.39927476]
 [ 0.33277308  0.46377177]
 [ 0.31958231  0.44764751]
 [ 0.28001     0.39927476]
 [ 0.28001     0.40464951]
 [ 0.47787155  0.46914652]
 [-1.26331005 -1.14865331]
 [ 0.33936847  0.44227276]
 [ 0.43829924  0.006918  ]
 [ 0.30639154  0.42077376]
 [ 0.29320077  0.42614851]
 [ 0.10193461  0.43152326]
 [ 0.33277308  0.45302226]
 [ 0.45149001  0.25415651]
 

In [ ]:
#fitting naive bayes to the training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [ ]:
GaussianNB()

GaussianNB()

In [ ]:
print(x_test)

[[ 0.29979616  0.39927476]
 [ 0.45149001  0.43152326]
 [ 0.18107923  0.42614851]
 [ 0.29979616  0.40464951]
 [ 0.31958231  0.46377177]
 [ 0.48446693  0.17353525]
 [ 0.24703308  0.32402826]
 [ 0.29979616  0.41002426]
 [-4.07953938 -3.18030889]
 [ 0.28001     0.37777576]
 [ 0.22724692  0.43152326]
 [ 0.28001     0.39390001]
 [ 0.43829924 -2.41171961]
 [ 0.29320077  0.41002426]
 [ 0.26022385  0.42614851]
 [ 0.27341462  0.39390001]
 [ 0.26681923 -0.20807201]
 [ 0.31298693  0.44227276]
 [ 0.28660539  0.38315051]
 [ 0.3261777   0.45839702]
 [ 0.48446693  0.1681605 ]
 [ 0.49106232  0.43152326]
 [ 0.29320077  0.41002426]
 [ 0.45149001 -0.01458101]
 [ 0.33277308  0.44764751]
 [ 0.30639154  0.43689801]
 [-1.13799774 -0.90678954]
 [ 0.45149001  0.23803226]
 [ 0.21405615  0.46914652]
 [ 0.3261777   0.44227276]
 [ 0.3261777   0.44227276]
 [ 0.27341462  0.43152326]
 [ 0.44489462  0.43152326]
 [ 0.3261777   0.45302226]]


In [ ]:
#predicting the test set results
y_pred = classifier.predict(x_test)
y_pred

array(['d', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'w', 'd', 'd', 'd', 'm',
       'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd',
       'm', 'd', 'd', 'd', 'd', 'd', 'd', 'd'], dtype='<U1')

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[31,  1,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

In [ ]:
y_pred = classifier.predict([[275, 1111]])
print(y_pred)

['m']
